services:
  mongodb:
    image: mongo:8
    container_name: local_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Abcd1234
      - MONGO_INITDB_DATABASE=local
    volumes:
      - localmongo:/data/db

volumes:
  localmongo:
